// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: digmode.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CloudlogHelper.CLHProto {

  /// <summary>Holder for reflection information generated from digmode.proto</summary>
  public static partial class DigmodeReflection {

    #region Descriptor
    /// <summary>File descriptor for digmode.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DigmodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1kaWdtb2RlLnByb3RvEg1jbGhfcHJvdG8ubXNnIpQBChJXc2p0eE1lc3Nh",
            "Z2VQYWNrZWQSJQoGc3RhdHVzGAEgASgLMhUuY2xoX3Byb3RvLm1zZy5TdGF0",
            "dXMSJgoHZGVjb2RlcxgCIAMoCzIVLmNsaF9wcm90by5tc2cuRGVjb2RlEi8K",
            "DHdzcHJfZGVjb2RlcxgDIAMoCzIZLmNsaF9wcm90by5tc2cuV1NQUkRlY29k",
            "ZSKwAQoMV3NqdHhNZXNzYWdlEicKBnN0YXR1cxgBIAEoCzIVLmNsaF9wcm90",
            "by5tc2cuU3RhdHVzSAASJwoGZGVjb2RlGAIgASgLMhUuY2xoX3Byb3RvLm1z",
            "Zy5EZWNvZGVIABIwCgt3c3ByX2RlY29kZRgDIAEoCzIZLmNsaF9wcm90by5t",
            "c2cuV1NQUkRlY29kZUgAEhEKCXRpbWVzdGFtcBhkIAEoA0IJCgdwYXlsb2Fk",
            "IrIBCgZEZWNvZGUSCwoDbmV3GAEgASgIEgwKBHRpbWUYAiABKA0SCwoDc25y",
            "GAMgASgFEhsKE29mZnNldF90aW1lX3NlY29uZHMYBCABKAISGwoTb2Zmc2V0",
            "X2ZyZXF1ZW5jeV9oehgFIAEoAhIMCgRtb2RlGAYgASgJEg8KB21lc3NhZ2UY",
            "ByABKAkSFgoObG93X2NvbmZpZGVuY2UYCCABKAgSDwoHb2ZmX2FpchgJIAEo",
            "CCLCAQoKV1NQUkRlY29kZRILCgNuZXcYASABKAgSDAoEdGltZRgCIAEoDRIL",
            "CgNzbnIYAyABKAUSGgoSZGVsdGFfdGltZV9zZWNvbmRzGAQgASgCEhQKDGZy",
            "ZXF1ZW5jeV9oehgFIAEoBBIaChJmcmVxdWVuY3lfZHJpZnRfaHoYBiABKAUS",
            "EAoIY2FsbHNpZ24YByABKAkSDAoEZ3JpZBgIIAEoCRINCgVwb3dlchgJIAEo",
            "DRIPCgdvZmZfYWlyGAogASgIIvEDCgZTdGF0dXMSGQoRZGlhbF9mcmVxdWVu",
            "Y3lfaHoYASABKAQSDAoEbW9kZRgCIAEoCRIPCgdkeF9jYWxsGAMgASgJEg4K",
            "BnJlcG9ydBgEIAEoCRIPCgd0eF9tb2RlGAUgASgJEhIKCnR4X2VuYWJsZWQY",
            "BiABKAgSFAoMdHJhbnNtaXR0aW5nGAcgASgIEhAKCGRlY29kaW5nGAggASgI",
            "Eh4KFnJ4X29mZnNldF9mcmVxdWVuY3lfaHoYCSABKA0SHgoWdHhfb2Zmc2V0",
            "X2ZyZXF1ZW5jeV9oehgKIAEoDRIPCgdkZV9jYWxsGAsgASgJEg8KB2RlX2dy",
            "aWQYDCABKAkSDwoHZHhfZ3JpZBgNIAEoCRITCgt0eF93YXRjaGRvZxgOIAEo",
            "CBIQCghzdWJfbW9kZRgPIAEoCRIRCglmYXN0X21vZGUYECABKAgSQwoWc3Bl",
            "Y2lhbF9vcGVyYXRpb25fbW9kZRgRIAEoDjIjLmNsaF9wcm90by5tc2cuU3Bl",
            "Y2lhbE9wZXJhdGlvbk1vZGUSGwoTZnJlcXVlbmN5X3RvbGVyYW5jZRgSIAEo",
            "DRIRCgl0cl9wZXJpb2QYEyABKA0SGgoSY29uZmlndXJhdGlvbl9uYW1lGBQg",
            "ASgJEhIKCnR4X21lc3NhZ2UYFSABKAkqZAoUU3BlY2lhbE9wZXJhdGlvbk1v",
            "ZGUSCAoETk9ORRAAEgkKBU5BVkhGEAESCQoFRVVWSEYQAxIMCghGSUVMRERB",
            "WRAEEgoKBlJUVFlSVRAFEgcKA0ZPWBAGEgkKBUhPVU5EEAdCRVopZ2l0aHVi",
            "LmNvbS9zeWRuZXlvd2wvY2xoLXNlcnZlci9jbGgtcHJvdG+qAhdDbG91ZGxv",
            "Z0hlbHBlci5DTEhQcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CloudlogHelper.CLHProto.SpecialOperationMode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CloudlogHelper.CLHProto.WsjtxMessagePacked), global::CloudlogHelper.CLHProto.WsjtxMessagePacked.Parser, new[]{ "Status", "Decodes", "WsprDecodes" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CloudlogHelper.CLHProto.WsjtxMessage), global::CloudlogHelper.CLHProto.WsjtxMessage.Parser, new[]{ "Status", "Decode", "WsprDecode", "Timestamp" }, new[]{ "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CloudlogHelper.CLHProto.Decode), global::CloudlogHelper.CLHProto.Decode.Parser, new[]{ "New", "Time", "Snr", "OffsetTimeSeconds", "OffsetFrequencyHz", "Mode", "Message", "LowConfidence", "OffAir" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CloudlogHelper.CLHProto.WSPRDecode), global::CloudlogHelper.CLHProto.WSPRDecode.Parser, new[]{ "New", "Time", "Snr", "DeltaTimeSeconds", "FrequencyHz", "FrequencyDriftHz", "Callsign", "Grid", "Power", "OffAir" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CloudlogHelper.CLHProto.Status), global::CloudlogHelper.CLHProto.Status.Parser, new[]{ "DialFrequencyHz", "Mode", "DxCall", "Report", "TxMode", "TxEnabled", "Transmitting", "Decoding", "RxOffsetFrequencyHz", "TxOffsetFrequencyHz", "DeCall", "DeGrid", "DxGrid", "TxWatchdog", "SubMode", "FastMode", "SpecialOperationMode", "FrequencyTolerance", "TrPeriod", "ConfigurationName", "TxMessage" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum SpecialOperationMode {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("NAVHF")] Navhf = 1,
    [pbr::OriginalName("EUVHF")] Euvhf = 3,
    [pbr::OriginalName("FIELDDAY")] Fieldday = 4,
    [pbr::OriginalName("RTTYRU")] Rttyru = 5,
    [pbr::OriginalName("FOX")] Fox = 6,
    [pbr::OriginalName("HOUND")] Hound = 7,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Server will pack all cached message and send to client at once.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WsjtxMessagePacked : pb::IMessage<WsjtxMessagePacked>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WsjtxMessagePacked> _parser = new pb::MessageParser<WsjtxMessagePacked>(() => new WsjtxMessagePacked());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WsjtxMessagePacked> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CloudlogHelper.CLHProto.DigmodeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WsjtxMessagePacked() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WsjtxMessagePacked(WsjtxMessagePacked other) : this() {
      status_ = other.status_ != null ? other.status_.Clone() : null;
      decodes_ = other.decodes_.Clone();
      wsprDecodes_ = other.wsprDecodes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WsjtxMessagePacked Clone() {
      return new WsjtxMessagePacked(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::CloudlogHelper.CLHProto.Status status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CloudlogHelper.CLHProto.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "decodes" field.</summary>
    public const int DecodesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::CloudlogHelper.CLHProto.Decode> _repeated_decodes_codec
        = pb::FieldCodec.ForMessage(18, global::CloudlogHelper.CLHProto.Decode.Parser);
    private readonly pbc::RepeatedField<global::CloudlogHelper.CLHProto.Decode> decodes_ = new pbc::RepeatedField<global::CloudlogHelper.CLHProto.Decode>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CloudlogHelper.CLHProto.Decode> Decodes {
      get { return decodes_; }
    }

    /// <summary>Field number for the "wspr_decodes" field.</summary>
    public const int WsprDecodesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::CloudlogHelper.CLHProto.WSPRDecode> _repeated_wsprDecodes_codec
        = pb::FieldCodec.ForMessage(26, global::CloudlogHelper.CLHProto.WSPRDecode.Parser);
    private readonly pbc::RepeatedField<global::CloudlogHelper.CLHProto.WSPRDecode> wsprDecodes_ = new pbc::RepeatedField<global::CloudlogHelper.CLHProto.WSPRDecode>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CloudlogHelper.CLHProto.WSPRDecode> WsprDecodes {
      get { return wsprDecodes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WsjtxMessagePacked);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WsjtxMessagePacked other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Status, other.Status)) return false;
      if(!decodes_.Equals(other.decodes_)) return false;
      if(!wsprDecodes_.Equals(other.wsprDecodes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (status_ != null) hash ^= Status.GetHashCode();
      hash ^= decodes_.GetHashCode();
      hash ^= wsprDecodes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (status_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Status);
      }
      decodes_.WriteTo(output, _repeated_decodes_codec);
      wsprDecodes_.WriteTo(output, _repeated_wsprDecodes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (status_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Status);
      }
      decodes_.WriteTo(ref output, _repeated_decodes_codec);
      wsprDecodes_.WriteTo(ref output, _repeated_wsprDecodes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (status_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Status);
      }
      size += decodes_.CalculateSize(_repeated_decodes_codec);
      size += wsprDecodes_.CalculateSize(_repeated_wsprDecodes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WsjtxMessagePacked other) {
      if (other == null) {
        return;
      }
      if (other.status_ != null) {
        if (status_ == null) {
          Status = new global::CloudlogHelper.CLHProto.Status();
        }
        Status.MergeFrom(other.Status);
      }
      decodes_.Add(other.decodes_);
      wsprDecodes_.Add(other.wsprDecodes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (status_ == null) {
              Status = new global::CloudlogHelper.CLHProto.Status();
            }
            input.ReadMessage(Status);
            break;
          }
          case 18: {
            decodes_.AddEntriesFrom(input, _repeated_decodes_codec);
            break;
          }
          case 26: {
            wsprDecodes_.AddEntriesFrom(input, _repeated_wsprDecodes_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (status_ == null) {
              Status = new global::CloudlogHelper.CLHProto.Status();
            }
            input.ReadMessage(Status);
            break;
          }
          case 18: {
            decodes_.AddEntriesFrom(ref input, _repeated_decodes_codec);
            break;
          }
          case 26: {
            wsprDecodes_.AddEntriesFrom(ref input, _repeated_wsprDecodes_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WsjtxMessage : pb::IMessage<WsjtxMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WsjtxMessage> _parser = new pb::MessageParser<WsjtxMessage>(() => new WsjtxMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WsjtxMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CloudlogHelper.CLHProto.DigmodeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WsjtxMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WsjtxMessage(WsjtxMessage other) : this() {
      timestamp_ = other.timestamp_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.Status:
          Status = other.Status.Clone();
          break;
        case PayloadOneofCase.Decode:
          Decode = other.Decode.Clone();
          break;
        case PayloadOneofCase.WsprDecode:
          WsprDecode = other.WsprDecode.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WsjtxMessage Clone() {
      return new WsjtxMessage(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CloudlogHelper.CLHProto.Status Status {
      get { return payloadCase_ == PayloadOneofCase.Status ? (global::CloudlogHelper.CLHProto.Status) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Status;
      }
    }

    /// <summary>Field number for the "decode" field.</summary>
    public const int DecodeFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CloudlogHelper.CLHProto.Decode Decode {
      get { return payloadCase_ == PayloadOneofCase.Decode ? (global::CloudlogHelper.CLHProto.Decode) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Decode;
      }
    }

    /// <summary>Field number for the "wspr_decode" field.</summary>
    public const int WsprDecodeFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CloudlogHelper.CLHProto.WSPRDecode WsprDecode {
      get { return payloadCase_ == PayloadOneofCase.WsprDecode ? (global::CloudlogHelper.CLHProto.WSPRDecode) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.WsprDecode;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 100;
    private long timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Status = 1,
      Decode = 2,
      WsprDecode = 3,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WsjtxMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WsjtxMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Status, other.Status)) return false;
      if (!object.Equals(Decode, other.Decode)) return false;
      if (!object.Equals(WsprDecode, other.WsprDecode)) return false;
      if (Timestamp != other.Timestamp) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (payloadCase_ == PayloadOneofCase.Status) hash ^= Status.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Decode) hash ^= Decode.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.WsprDecode) hash ^= WsprDecode.GetHashCode();
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (payloadCase_ == PayloadOneofCase.Status) {
        output.WriteRawTag(10);
        output.WriteMessage(Status);
      }
      if (payloadCase_ == PayloadOneofCase.Decode) {
        output.WriteRawTag(18);
        output.WriteMessage(Decode);
      }
      if (payloadCase_ == PayloadOneofCase.WsprDecode) {
        output.WriteRawTag(26);
        output.WriteMessage(WsprDecode);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(160, 6);
        output.WriteInt64(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (payloadCase_ == PayloadOneofCase.Status) {
        output.WriteRawTag(10);
        output.WriteMessage(Status);
      }
      if (payloadCase_ == PayloadOneofCase.Decode) {
        output.WriteRawTag(18);
        output.WriteMessage(Decode);
      }
      if (payloadCase_ == PayloadOneofCase.WsprDecode) {
        output.WriteRawTag(26);
        output.WriteMessage(WsprDecode);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(160, 6);
        output.WriteInt64(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (payloadCase_ == PayloadOneofCase.Status) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Status);
      }
      if (payloadCase_ == PayloadOneofCase.Decode) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Decode);
      }
      if (payloadCase_ == PayloadOneofCase.WsprDecode) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(WsprDecode);
      }
      if (Timestamp != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WsjtxMessage other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Status:
          if (Status == null) {
            Status = new global::CloudlogHelper.CLHProto.Status();
          }
          Status.MergeFrom(other.Status);
          break;
        case PayloadOneofCase.Decode:
          if (Decode == null) {
            Decode = new global::CloudlogHelper.CLHProto.Decode();
          }
          Decode.MergeFrom(other.Decode);
          break;
        case PayloadOneofCase.WsprDecode:
          if (WsprDecode == null) {
            WsprDecode = new global::CloudlogHelper.CLHProto.WSPRDecode();
          }
          WsprDecode.MergeFrom(other.WsprDecode);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::CloudlogHelper.CLHProto.Status subBuilder = new global::CloudlogHelper.CLHProto.Status();
            if (payloadCase_ == PayloadOneofCase.Status) {
              subBuilder.MergeFrom(Status);
            }
            input.ReadMessage(subBuilder);
            Status = subBuilder;
            break;
          }
          case 18: {
            global::CloudlogHelper.CLHProto.Decode subBuilder = new global::CloudlogHelper.CLHProto.Decode();
            if (payloadCase_ == PayloadOneofCase.Decode) {
              subBuilder.MergeFrom(Decode);
            }
            input.ReadMessage(subBuilder);
            Decode = subBuilder;
            break;
          }
          case 26: {
            global::CloudlogHelper.CLHProto.WSPRDecode subBuilder = new global::CloudlogHelper.CLHProto.WSPRDecode();
            if (payloadCase_ == PayloadOneofCase.WsprDecode) {
              subBuilder.MergeFrom(WsprDecode);
            }
            input.ReadMessage(subBuilder);
            WsprDecode = subBuilder;
            break;
          }
          case 800: {
            Timestamp = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::CloudlogHelper.CLHProto.Status subBuilder = new global::CloudlogHelper.CLHProto.Status();
            if (payloadCase_ == PayloadOneofCase.Status) {
              subBuilder.MergeFrom(Status);
            }
            input.ReadMessage(subBuilder);
            Status = subBuilder;
            break;
          }
          case 18: {
            global::CloudlogHelper.CLHProto.Decode subBuilder = new global::CloudlogHelper.CLHProto.Decode();
            if (payloadCase_ == PayloadOneofCase.Decode) {
              subBuilder.MergeFrom(Decode);
            }
            input.ReadMessage(subBuilder);
            Decode = subBuilder;
            break;
          }
          case 26: {
            global::CloudlogHelper.CLHProto.WSPRDecode subBuilder = new global::CloudlogHelper.CLHProto.WSPRDecode();
            if (payloadCase_ == PayloadOneofCase.WsprDecode) {
              subBuilder.MergeFrom(WsprDecode);
            }
            input.ReadMessage(subBuilder);
            WsprDecode = subBuilder;
            break;
          }
          case 800: {
            Timestamp = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Decode : pb::IMessage<Decode>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Decode> _parser = new pb::MessageParser<Decode>(() => new Decode());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Decode> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CloudlogHelper.CLHProto.DigmodeReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Decode() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Decode(Decode other) : this() {
      new_ = other.new_;
      time_ = other.time_;
      snr_ = other.snr_;
      offsetTimeSeconds_ = other.offsetTimeSeconds_;
      offsetFrequencyHz_ = other.offsetFrequencyHz_;
      mode_ = other.mode_;
      message_ = other.message_;
      lowConfidence_ = other.lowConfidence_;
      offAir_ = other.offAir_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Decode Clone() {
      return new Decode(this);
    }

    /// <summary>Field number for the "new" field.</summary>
    public const int NewFieldNumber = 1;
    private bool new_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool New {
      get { return new_; }
      set {
        new_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 2;
    private uint time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "snr" field.</summary>
    public const int SnrFieldNumber = 3;
    private int snr_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Snr {
      get { return snr_; }
      set {
        snr_ = value;
      }
    }

    /// <summary>Field number for the "offset_time_seconds" field.</summary>
    public const int OffsetTimeSecondsFieldNumber = 4;
    private float offsetTimeSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float OffsetTimeSeconds {
      get { return offsetTimeSeconds_; }
      set {
        offsetTimeSeconds_ = value;
      }
    }

    /// <summary>Field number for the "offset_frequency_hz" field.</summary>
    public const int OffsetFrequencyHzFieldNumber = 5;
    private float offsetFrequencyHz_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float OffsetFrequencyHz {
      get { return offsetFrequencyHz_; }
      set {
        offsetFrequencyHz_ = value;
      }
    }

    /// <summary>Field number for the "mode" field.</summary>
    public const int ModeFieldNumber = 6;
    private string mode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Mode {
      get { return mode_; }
      set {
        mode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 7;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "low_confidence" field.</summary>
    public const int LowConfidenceFieldNumber = 8;
    private bool lowConfidence_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool LowConfidence {
      get { return lowConfidence_; }
      set {
        lowConfidence_ = value;
      }
    }

    /// <summary>Field number for the "off_air" field.</summary>
    public const int OffAirFieldNumber = 9;
    private bool offAir_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OffAir {
      get { return offAir_; }
      set {
        offAir_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Decode);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Decode other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (New != other.New) return false;
      if (Time != other.Time) return false;
      if (Snr != other.Snr) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(OffsetTimeSeconds, other.OffsetTimeSeconds)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(OffsetFrequencyHz, other.OffsetFrequencyHz)) return false;
      if (Mode != other.Mode) return false;
      if (Message != other.Message) return false;
      if (LowConfidence != other.LowConfidence) return false;
      if (OffAir != other.OffAir) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (New != false) hash ^= New.GetHashCode();
      if (Time != 0) hash ^= Time.GetHashCode();
      if (Snr != 0) hash ^= Snr.GetHashCode();
      if (OffsetTimeSeconds != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(OffsetTimeSeconds);
      if (OffsetFrequencyHz != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(OffsetFrequencyHz);
      if (Mode.Length != 0) hash ^= Mode.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (LowConfidence != false) hash ^= LowConfidence.GetHashCode();
      if (OffAir != false) hash ^= OffAir.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (New != false) {
        output.WriteRawTag(8);
        output.WriteBool(New);
      }
      if (Time != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Time);
      }
      if (Snr != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Snr);
      }
      if (OffsetTimeSeconds != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(OffsetTimeSeconds);
      }
      if (OffsetFrequencyHz != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(OffsetFrequencyHz);
      }
      if (Mode.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Mode);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Message);
      }
      if (LowConfidence != false) {
        output.WriteRawTag(64);
        output.WriteBool(LowConfidence);
      }
      if (OffAir != false) {
        output.WriteRawTag(72);
        output.WriteBool(OffAir);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (New != false) {
        output.WriteRawTag(8);
        output.WriteBool(New);
      }
      if (Time != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Time);
      }
      if (Snr != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Snr);
      }
      if (OffsetTimeSeconds != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(OffsetTimeSeconds);
      }
      if (OffsetFrequencyHz != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(OffsetFrequencyHz);
      }
      if (Mode.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Mode);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Message);
      }
      if (LowConfidence != false) {
        output.WriteRawTag(64);
        output.WriteBool(LowConfidence);
      }
      if (OffAir != false) {
        output.WriteRawTag(72);
        output.WriteBool(OffAir);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (New != false) {
        size += 1 + 1;
      }
      if (Time != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Time);
      }
      if (Snr != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Snr);
      }
      if (OffsetTimeSeconds != 0F) {
        size += 1 + 4;
      }
      if (OffsetFrequencyHz != 0F) {
        size += 1 + 4;
      }
      if (Mode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mode);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (LowConfidence != false) {
        size += 1 + 1;
      }
      if (OffAir != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Decode other) {
      if (other == null) {
        return;
      }
      if (other.New != false) {
        New = other.New;
      }
      if (other.Time != 0) {
        Time = other.Time;
      }
      if (other.Snr != 0) {
        Snr = other.Snr;
      }
      if (other.OffsetTimeSeconds != 0F) {
        OffsetTimeSeconds = other.OffsetTimeSeconds;
      }
      if (other.OffsetFrequencyHz != 0F) {
        OffsetFrequencyHz = other.OffsetFrequencyHz;
      }
      if (other.Mode.Length != 0) {
        Mode = other.Mode;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.LowConfidence != false) {
        LowConfidence = other.LowConfidence;
      }
      if (other.OffAir != false) {
        OffAir = other.OffAir;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            New = input.ReadBool();
            break;
          }
          case 16: {
            Time = input.ReadUInt32();
            break;
          }
          case 24: {
            Snr = input.ReadInt32();
            break;
          }
          case 37: {
            OffsetTimeSeconds = input.ReadFloat();
            break;
          }
          case 45: {
            OffsetFrequencyHz = input.ReadFloat();
            break;
          }
          case 50: {
            Mode = input.ReadString();
            break;
          }
          case 58: {
            Message = input.ReadString();
            break;
          }
          case 64: {
            LowConfidence = input.ReadBool();
            break;
          }
          case 72: {
            OffAir = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            New = input.ReadBool();
            break;
          }
          case 16: {
            Time = input.ReadUInt32();
            break;
          }
          case 24: {
            Snr = input.ReadInt32();
            break;
          }
          case 37: {
            OffsetTimeSeconds = input.ReadFloat();
            break;
          }
          case 45: {
            OffsetFrequencyHz = input.ReadFloat();
            break;
          }
          case 50: {
            Mode = input.ReadString();
            break;
          }
          case 58: {
            Message = input.ReadString();
            break;
          }
          case 64: {
            LowConfidence = input.ReadBool();
            break;
          }
          case 72: {
            OffAir = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WSPRDecode : pb::IMessage<WSPRDecode>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WSPRDecode> _parser = new pb::MessageParser<WSPRDecode>(() => new WSPRDecode());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WSPRDecode> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CloudlogHelper.CLHProto.DigmodeReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WSPRDecode() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WSPRDecode(WSPRDecode other) : this() {
      new_ = other.new_;
      time_ = other.time_;
      snr_ = other.snr_;
      deltaTimeSeconds_ = other.deltaTimeSeconds_;
      frequencyHz_ = other.frequencyHz_;
      frequencyDriftHz_ = other.frequencyDriftHz_;
      callsign_ = other.callsign_;
      grid_ = other.grid_;
      power_ = other.power_;
      offAir_ = other.offAir_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WSPRDecode Clone() {
      return new WSPRDecode(this);
    }

    /// <summary>Field number for the "new" field.</summary>
    public const int NewFieldNumber = 1;
    private bool new_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool New {
      get { return new_; }
      set {
        new_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 2;
    private uint time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "snr" field.</summary>
    public const int SnrFieldNumber = 3;
    private int snr_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Snr {
      get { return snr_; }
      set {
        snr_ = value;
      }
    }

    /// <summary>Field number for the "delta_time_seconds" field.</summary>
    public const int DeltaTimeSecondsFieldNumber = 4;
    private float deltaTimeSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float DeltaTimeSeconds {
      get { return deltaTimeSeconds_; }
      set {
        deltaTimeSeconds_ = value;
      }
    }

    /// <summary>Field number for the "frequency_hz" field.</summary>
    public const int FrequencyHzFieldNumber = 5;
    private ulong frequencyHz_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong FrequencyHz {
      get { return frequencyHz_; }
      set {
        frequencyHz_ = value;
      }
    }

    /// <summary>Field number for the "frequency_drift_hz" field.</summary>
    public const int FrequencyDriftHzFieldNumber = 6;
    private int frequencyDriftHz_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FrequencyDriftHz {
      get { return frequencyDriftHz_; }
      set {
        frequencyDriftHz_ = value;
      }
    }

    /// <summary>Field number for the "callsign" field.</summary>
    public const int CallsignFieldNumber = 7;
    private string callsign_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Callsign {
      get { return callsign_; }
      set {
        callsign_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "grid" field.</summary>
    public const int GridFieldNumber = 8;
    private string grid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Grid {
      get { return grid_; }
      set {
        grid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "power" field.</summary>
    public const int PowerFieldNumber = 9;
    private uint power_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Power {
      get { return power_; }
      set {
        power_ = value;
      }
    }

    /// <summary>Field number for the "off_air" field.</summary>
    public const int OffAirFieldNumber = 10;
    private bool offAir_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OffAir {
      get { return offAir_; }
      set {
        offAir_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WSPRDecode);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WSPRDecode other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (New != other.New) return false;
      if (Time != other.Time) return false;
      if (Snr != other.Snr) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DeltaTimeSeconds, other.DeltaTimeSeconds)) return false;
      if (FrequencyHz != other.FrequencyHz) return false;
      if (FrequencyDriftHz != other.FrequencyDriftHz) return false;
      if (Callsign != other.Callsign) return false;
      if (Grid != other.Grid) return false;
      if (Power != other.Power) return false;
      if (OffAir != other.OffAir) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (New != false) hash ^= New.GetHashCode();
      if (Time != 0) hash ^= Time.GetHashCode();
      if (Snr != 0) hash ^= Snr.GetHashCode();
      if (DeltaTimeSeconds != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DeltaTimeSeconds);
      if (FrequencyHz != 0UL) hash ^= FrequencyHz.GetHashCode();
      if (FrequencyDriftHz != 0) hash ^= FrequencyDriftHz.GetHashCode();
      if (Callsign.Length != 0) hash ^= Callsign.GetHashCode();
      if (Grid.Length != 0) hash ^= Grid.GetHashCode();
      if (Power != 0) hash ^= Power.GetHashCode();
      if (OffAir != false) hash ^= OffAir.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (New != false) {
        output.WriteRawTag(8);
        output.WriteBool(New);
      }
      if (Time != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Time);
      }
      if (Snr != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Snr);
      }
      if (DeltaTimeSeconds != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(DeltaTimeSeconds);
      }
      if (FrequencyHz != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(FrequencyHz);
      }
      if (FrequencyDriftHz != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(FrequencyDriftHz);
      }
      if (Callsign.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Callsign);
      }
      if (Grid.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Grid);
      }
      if (Power != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Power);
      }
      if (OffAir != false) {
        output.WriteRawTag(80);
        output.WriteBool(OffAir);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (New != false) {
        output.WriteRawTag(8);
        output.WriteBool(New);
      }
      if (Time != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Time);
      }
      if (Snr != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Snr);
      }
      if (DeltaTimeSeconds != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(DeltaTimeSeconds);
      }
      if (FrequencyHz != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(FrequencyHz);
      }
      if (FrequencyDriftHz != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(FrequencyDriftHz);
      }
      if (Callsign.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Callsign);
      }
      if (Grid.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Grid);
      }
      if (Power != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Power);
      }
      if (OffAir != false) {
        output.WriteRawTag(80);
        output.WriteBool(OffAir);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (New != false) {
        size += 1 + 1;
      }
      if (Time != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Time);
      }
      if (Snr != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Snr);
      }
      if (DeltaTimeSeconds != 0F) {
        size += 1 + 4;
      }
      if (FrequencyHz != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(FrequencyHz);
      }
      if (FrequencyDriftHz != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FrequencyDriftHz);
      }
      if (Callsign.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Callsign);
      }
      if (Grid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Grid);
      }
      if (Power != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Power);
      }
      if (OffAir != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WSPRDecode other) {
      if (other == null) {
        return;
      }
      if (other.New != false) {
        New = other.New;
      }
      if (other.Time != 0) {
        Time = other.Time;
      }
      if (other.Snr != 0) {
        Snr = other.Snr;
      }
      if (other.DeltaTimeSeconds != 0F) {
        DeltaTimeSeconds = other.DeltaTimeSeconds;
      }
      if (other.FrequencyHz != 0UL) {
        FrequencyHz = other.FrequencyHz;
      }
      if (other.FrequencyDriftHz != 0) {
        FrequencyDriftHz = other.FrequencyDriftHz;
      }
      if (other.Callsign.Length != 0) {
        Callsign = other.Callsign;
      }
      if (other.Grid.Length != 0) {
        Grid = other.Grid;
      }
      if (other.Power != 0) {
        Power = other.Power;
      }
      if (other.OffAir != false) {
        OffAir = other.OffAir;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            New = input.ReadBool();
            break;
          }
          case 16: {
            Time = input.ReadUInt32();
            break;
          }
          case 24: {
            Snr = input.ReadInt32();
            break;
          }
          case 37: {
            DeltaTimeSeconds = input.ReadFloat();
            break;
          }
          case 40: {
            FrequencyHz = input.ReadUInt64();
            break;
          }
          case 48: {
            FrequencyDriftHz = input.ReadInt32();
            break;
          }
          case 58: {
            Callsign = input.ReadString();
            break;
          }
          case 66: {
            Grid = input.ReadString();
            break;
          }
          case 72: {
            Power = input.ReadUInt32();
            break;
          }
          case 80: {
            OffAir = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            New = input.ReadBool();
            break;
          }
          case 16: {
            Time = input.ReadUInt32();
            break;
          }
          case 24: {
            Snr = input.ReadInt32();
            break;
          }
          case 37: {
            DeltaTimeSeconds = input.ReadFloat();
            break;
          }
          case 40: {
            FrequencyHz = input.ReadUInt64();
            break;
          }
          case 48: {
            FrequencyDriftHz = input.ReadInt32();
            break;
          }
          case 58: {
            Callsign = input.ReadString();
            break;
          }
          case 66: {
            Grid = input.ReadString();
            break;
          }
          case 72: {
            Power = input.ReadUInt32();
            break;
          }
          case 80: {
            OffAir = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Status : pb::IMessage<Status>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Status> _parser = new pb::MessageParser<Status>(() => new Status());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Status> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CloudlogHelper.CLHProto.DigmodeReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Status() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Status(Status other) : this() {
      dialFrequencyHz_ = other.dialFrequencyHz_;
      mode_ = other.mode_;
      dxCall_ = other.dxCall_;
      report_ = other.report_;
      txMode_ = other.txMode_;
      txEnabled_ = other.txEnabled_;
      transmitting_ = other.transmitting_;
      decoding_ = other.decoding_;
      rxOffsetFrequencyHz_ = other.rxOffsetFrequencyHz_;
      txOffsetFrequencyHz_ = other.txOffsetFrequencyHz_;
      deCall_ = other.deCall_;
      deGrid_ = other.deGrid_;
      dxGrid_ = other.dxGrid_;
      txWatchdog_ = other.txWatchdog_;
      subMode_ = other.subMode_;
      fastMode_ = other.fastMode_;
      specialOperationMode_ = other.specialOperationMode_;
      frequencyTolerance_ = other.frequencyTolerance_;
      trPeriod_ = other.trPeriod_;
      configurationName_ = other.configurationName_;
      txMessage_ = other.txMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Status Clone() {
      return new Status(this);
    }

    /// <summary>Field number for the "dial_frequency_hz" field.</summary>
    public const int DialFrequencyHzFieldNumber = 1;
    private ulong dialFrequencyHz_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong DialFrequencyHz {
      get { return dialFrequencyHz_; }
      set {
        dialFrequencyHz_ = value;
      }
    }

    /// <summary>Field number for the "mode" field.</summary>
    public const int ModeFieldNumber = 2;
    private string mode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Mode {
      get { return mode_; }
      set {
        mode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dx_call" field.</summary>
    public const int DxCallFieldNumber = 3;
    private string dxCall_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DxCall {
      get { return dxCall_; }
      set {
        dxCall_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "report" field.</summary>
    public const int ReportFieldNumber = 4;
    private string report_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Report {
      get { return report_; }
      set {
        report_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tx_mode" field.</summary>
    public const int TxModeFieldNumber = 5;
    private string txMode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TxMode {
      get { return txMode_; }
      set {
        txMode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tx_enabled" field.</summary>
    public const int TxEnabledFieldNumber = 6;
    private bool txEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool TxEnabled {
      get { return txEnabled_; }
      set {
        txEnabled_ = value;
      }
    }

    /// <summary>Field number for the "transmitting" field.</summary>
    public const int TransmittingFieldNumber = 7;
    private bool transmitting_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Transmitting {
      get { return transmitting_; }
      set {
        transmitting_ = value;
      }
    }

    /// <summary>Field number for the "decoding" field.</summary>
    public const int DecodingFieldNumber = 8;
    private bool decoding_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Decoding {
      get { return decoding_; }
      set {
        decoding_ = value;
      }
    }

    /// <summary>Field number for the "rx_offset_frequency_hz" field.</summary>
    public const int RxOffsetFrequencyHzFieldNumber = 9;
    private uint rxOffsetFrequencyHz_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RxOffsetFrequencyHz {
      get { return rxOffsetFrequencyHz_; }
      set {
        rxOffsetFrequencyHz_ = value;
      }
    }

    /// <summary>Field number for the "tx_offset_frequency_hz" field.</summary>
    public const int TxOffsetFrequencyHzFieldNumber = 10;
    private uint txOffsetFrequencyHz_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TxOffsetFrequencyHz {
      get { return txOffsetFrequencyHz_; }
      set {
        txOffsetFrequencyHz_ = value;
      }
    }

    /// <summary>Field number for the "de_call" field.</summary>
    public const int DeCallFieldNumber = 11;
    private string deCall_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeCall {
      get { return deCall_; }
      set {
        deCall_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "de_grid" field.</summary>
    public const int DeGridFieldNumber = 12;
    private string deGrid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeGrid {
      get { return deGrid_; }
      set {
        deGrid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dx_grid" field.</summary>
    public const int DxGridFieldNumber = 13;
    private string dxGrid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DxGrid {
      get { return dxGrid_; }
      set {
        dxGrid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tx_watchdog" field.</summary>
    public const int TxWatchdogFieldNumber = 14;
    private bool txWatchdog_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool TxWatchdog {
      get { return txWatchdog_; }
      set {
        txWatchdog_ = value;
      }
    }

    /// <summary>Field number for the "sub_mode" field.</summary>
    public const int SubModeFieldNumber = 15;
    private string subMode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SubMode {
      get { return subMode_; }
      set {
        subMode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fast_mode" field.</summary>
    public const int FastModeFieldNumber = 16;
    private bool fastMode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool FastMode {
      get { return fastMode_; }
      set {
        fastMode_ = value;
      }
    }

    /// <summary>Field number for the "special_operation_mode" field.</summary>
    public const int SpecialOperationModeFieldNumber = 17;
    private global::CloudlogHelper.CLHProto.SpecialOperationMode specialOperationMode_ = global::CloudlogHelper.CLHProto.SpecialOperationMode.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CloudlogHelper.CLHProto.SpecialOperationMode SpecialOperationMode {
      get { return specialOperationMode_; }
      set {
        specialOperationMode_ = value;
      }
    }

    /// <summary>Field number for the "frequency_tolerance" field.</summary>
    public const int FrequencyToleranceFieldNumber = 18;
    private uint frequencyTolerance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FrequencyTolerance {
      get { return frequencyTolerance_; }
      set {
        frequencyTolerance_ = value;
      }
    }

    /// <summary>Field number for the "tr_period" field.</summary>
    public const int TrPeriodFieldNumber = 19;
    private uint trPeriod_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TrPeriod {
      get { return trPeriod_; }
      set {
        trPeriod_ = value;
      }
    }

    /// <summary>Field number for the "configuration_name" field.</summary>
    public const int ConfigurationNameFieldNumber = 20;
    private string configurationName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ConfigurationName {
      get { return configurationName_; }
      set {
        configurationName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tx_message" field.</summary>
    public const int TxMessageFieldNumber = 21;
    private string txMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TxMessage {
      get { return txMessage_; }
      set {
        txMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Status);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Status other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DialFrequencyHz != other.DialFrequencyHz) return false;
      if (Mode != other.Mode) return false;
      if (DxCall != other.DxCall) return false;
      if (Report != other.Report) return false;
      if (TxMode != other.TxMode) return false;
      if (TxEnabled != other.TxEnabled) return false;
      if (Transmitting != other.Transmitting) return false;
      if (Decoding != other.Decoding) return false;
      if (RxOffsetFrequencyHz != other.RxOffsetFrequencyHz) return false;
      if (TxOffsetFrequencyHz != other.TxOffsetFrequencyHz) return false;
      if (DeCall != other.DeCall) return false;
      if (DeGrid != other.DeGrid) return false;
      if (DxGrid != other.DxGrid) return false;
      if (TxWatchdog != other.TxWatchdog) return false;
      if (SubMode != other.SubMode) return false;
      if (FastMode != other.FastMode) return false;
      if (SpecialOperationMode != other.SpecialOperationMode) return false;
      if (FrequencyTolerance != other.FrequencyTolerance) return false;
      if (TrPeriod != other.TrPeriod) return false;
      if (ConfigurationName != other.ConfigurationName) return false;
      if (TxMessage != other.TxMessage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DialFrequencyHz != 0UL) hash ^= DialFrequencyHz.GetHashCode();
      if (Mode.Length != 0) hash ^= Mode.GetHashCode();
      if (DxCall.Length != 0) hash ^= DxCall.GetHashCode();
      if (Report.Length != 0) hash ^= Report.GetHashCode();
      if (TxMode.Length != 0) hash ^= TxMode.GetHashCode();
      if (TxEnabled != false) hash ^= TxEnabled.GetHashCode();
      if (Transmitting != false) hash ^= Transmitting.GetHashCode();
      if (Decoding != false) hash ^= Decoding.GetHashCode();
      if (RxOffsetFrequencyHz != 0) hash ^= RxOffsetFrequencyHz.GetHashCode();
      if (TxOffsetFrequencyHz != 0) hash ^= TxOffsetFrequencyHz.GetHashCode();
      if (DeCall.Length != 0) hash ^= DeCall.GetHashCode();
      if (DeGrid.Length != 0) hash ^= DeGrid.GetHashCode();
      if (DxGrid.Length != 0) hash ^= DxGrid.GetHashCode();
      if (TxWatchdog != false) hash ^= TxWatchdog.GetHashCode();
      if (SubMode.Length != 0) hash ^= SubMode.GetHashCode();
      if (FastMode != false) hash ^= FastMode.GetHashCode();
      if (SpecialOperationMode != global::CloudlogHelper.CLHProto.SpecialOperationMode.None) hash ^= SpecialOperationMode.GetHashCode();
      if (FrequencyTolerance != 0) hash ^= FrequencyTolerance.GetHashCode();
      if (TrPeriod != 0) hash ^= TrPeriod.GetHashCode();
      if (ConfigurationName.Length != 0) hash ^= ConfigurationName.GetHashCode();
      if (TxMessage.Length != 0) hash ^= TxMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DialFrequencyHz != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(DialFrequencyHz);
      }
      if (Mode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Mode);
      }
      if (DxCall.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DxCall);
      }
      if (Report.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Report);
      }
      if (TxMode.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(TxMode);
      }
      if (TxEnabled != false) {
        output.WriteRawTag(48);
        output.WriteBool(TxEnabled);
      }
      if (Transmitting != false) {
        output.WriteRawTag(56);
        output.WriteBool(Transmitting);
      }
      if (Decoding != false) {
        output.WriteRawTag(64);
        output.WriteBool(Decoding);
      }
      if (RxOffsetFrequencyHz != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(RxOffsetFrequencyHz);
      }
      if (TxOffsetFrequencyHz != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(TxOffsetFrequencyHz);
      }
      if (DeCall.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(DeCall);
      }
      if (DeGrid.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(DeGrid);
      }
      if (DxGrid.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(DxGrid);
      }
      if (TxWatchdog != false) {
        output.WriteRawTag(112);
        output.WriteBool(TxWatchdog);
      }
      if (SubMode.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(SubMode);
      }
      if (FastMode != false) {
        output.WriteRawTag(128, 1);
        output.WriteBool(FastMode);
      }
      if (SpecialOperationMode != global::CloudlogHelper.CLHProto.SpecialOperationMode.None) {
        output.WriteRawTag(136, 1);
        output.WriteEnum((int) SpecialOperationMode);
      }
      if (FrequencyTolerance != 0) {
        output.WriteRawTag(144, 1);
        output.WriteUInt32(FrequencyTolerance);
      }
      if (TrPeriod != 0) {
        output.WriteRawTag(152, 1);
        output.WriteUInt32(TrPeriod);
      }
      if (ConfigurationName.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(ConfigurationName);
      }
      if (TxMessage.Length != 0) {
        output.WriteRawTag(170, 1);
        output.WriteString(TxMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DialFrequencyHz != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(DialFrequencyHz);
      }
      if (Mode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Mode);
      }
      if (DxCall.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DxCall);
      }
      if (Report.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Report);
      }
      if (TxMode.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(TxMode);
      }
      if (TxEnabled != false) {
        output.WriteRawTag(48);
        output.WriteBool(TxEnabled);
      }
      if (Transmitting != false) {
        output.WriteRawTag(56);
        output.WriteBool(Transmitting);
      }
      if (Decoding != false) {
        output.WriteRawTag(64);
        output.WriteBool(Decoding);
      }
      if (RxOffsetFrequencyHz != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(RxOffsetFrequencyHz);
      }
      if (TxOffsetFrequencyHz != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(TxOffsetFrequencyHz);
      }
      if (DeCall.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(DeCall);
      }
      if (DeGrid.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(DeGrid);
      }
      if (DxGrid.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(DxGrid);
      }
      if (TxWatchdog != false) {
        output.WriteRawTag(112);
        output.WriteBool(TxWatchdog);
      }
      if (SubMode.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(SubMode);
      }
      if (FastMode != false) {
        output.WriteRawTag(128, 1);
        output.WriteBool(FastMode);
      }
      if (SpecialOperationMode != global::CloudlogHelper.CLHProto.SpecialOperationMode.None) {
        output.WriteRawTag(136, 1);
        output.WriteEnum((int) SpecialOperationMode);
      }
      if (FrequencyTolerance != 0) {
        output.WriteRawTag(144, 1);
        output.WriteUInt32(FrequencyTolerance);
      }
      if (TrPeriod != 0) {
        output.WriteRawTag(152, 1);
        output.WriteUInt32(TrPeriod);
      }
      if (ConfigurationName.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(ConfigurationName);
      }
      if (TxMessage.Length != 0) {
        output.WriteRawTag(170, 1);
        output.WriteString(TxMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DialFrequencyHz != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(DialFrequencyHz);
      }
      if (Mode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mode);
      }
      if (DxCall.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DxCall);
      }
      if (Report.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Report);
      }
      if (TxMode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TxMode);
      }
      if (TxEnabled != false) {
        size += 1 + 1;
      }
      if (Transmitting != false) {
        size += 1 + 1;
      }
      if (Decoding != false) {
        size += 1 + 1;
      }
      if (RxOffsetFrequencyHz != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RxOffsetFrequencyHz);
      }
      if (TxOffsetFrequencyHz != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TxOffsetFrequencyHz);
      }
      if (DeCall.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeCall);
      }
      if (DeGrid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeGrid);
      }
      if (DxGrid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DxGrid);
      }
      if (TxWatchdog != false) {
        size += 1 + 1;
      }
      if (SubMode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SubMode);
      }
      if (FastMode != false) {
        size += 2 + 1;
      }
      if (SpecialOperationMode != global::CloudlogHelper.CLHProto.SpecialOperationMode.None) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) SpecialOperationMode);
      }
      if (FrequencyTolerance != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(FrequencyTolerance);
      }
      if (TrPeriod != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(TrPeriod);
      }
      if (ConfigurationName.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ConfigurationName);
      }
      if (TxMessage.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(TxMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Status other) {
      if (other == null) {
        return;
      }
      if (other.DialFrequencyHz != 0UL) {
        DialFrequencyHz = other.DialFrequencyHz;
      }
      if (other.Mode.Length != 0) {
        Mode = other.Mode;
      }
      if (other.DxCall.Length != 0) {
        DxCall = other.DxCall;
      }
      if (other.Report.Length != 0) {
        Report = other.Report;
      }
      if (other.TxMode.Length != 0) {
        TxMode = other.TxMode;
      }
      if (other.TxEnabled != false) {
        TxEnabled = other.TxEnabled;
      }
      if (other.Transmitting != false) {
        Transmitting = other.Transmitting;
      }
      if (other.Decoding != false) {
        Decoding = other.Decoding;
      }
      if (other.RxOffsetFrequencyHz != 0) {
        RxOffsetFrequencyHz = other.RxOffsetFrequencyHz;
      }
      if (other.TxOffsetFrequencyHz != 0) {
        TxOffsetFrequencyHz = other.TxOffsetFrequencyHz;
      }
      if (other.DeCall.Length != 0) {
        DeCall = other.DeCall;
      }
      if (other.DeGrid.Length != 0) {
        DeGrid = other.DeGrid;
      }
      if (other.DxGrid.Length != 0) {
        DxGrid = other.DxGrid;
      }
      if (other.TxWatchdog != false) {
        TxWatchdog = other.TxWatchdog;
      }
      if (other.SubMode.Length != 0) {
        SubMode = other.SubMode;
      }
      if (other.FastMode != false) {
        FastMode = other.FastMode;
      }
      if (other.SpecialOperationMode != global::CloudlogHelper.CLHProto.SpecialOperationMode.None) {
        SpecialOperationMode = other.SpecialOperationMode;
      }
      if (other.FrequencyTolerance != 0) {
        FrequencyTolerance = other.FrequencyTolerance;
      }
      if (other.TrPeriod != 0) {
        TrPeriod = other.TrPeriod;
      }
      if (other.ConfigurationName.Length != 0) {
        ConfigurationName = other.ConfigurationName;
      }
      if (other.TxMessage.Length != 0) {
        TxMessage = other.TxMessage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DialFrequencyHz = input.ReadUInt64();
            break;
          }
          case 18: {
            Mode = input.ReadString();
            break;
          }
          case 26: {
            DxCall = input.ReadString();
            break;
          }
          case 34: {
            Report = input.ReadString();
            break;
          }
          case 42: {
            TxMode = input.ReadString();
            break;
          }
          case 48: {
            TxEnabled = input.ReadBool();
            break;
          }
          case 56: {
            Transmitting = input.ReadBool();
            break;
          }
          case 64: {
            Decoding = input.ReadBool();
            break;
          }
          case 72: {
            RxOffsetFrequencyHz = input.ReadUInt32();
            break;
          }
          case 80: {
            TxOffsetFrequencyHz = input.ReadUInt32();
            break;
          }
          case 90: {
            DeCall = input.ReadString();
            break;
          }
          case 98: {
            DeGrid = input.ReadString();
            break;
          }
          case 106: {
            DxGrid = input.ReadString();
            break;
          }
          case 112: {
            TxWatchdog = input.ReadBool();
            break;
          }
          case 122: {
            SubMode = input.ReadString();
            break;
          }
          case 128: {
            FastMode = input.ReadBool();
            break;
          }
          case 136: {
            SpecialOperationMode = (global::CloudlogHelper.CLHProto.SpecialOperationMode) input.ReadEnum();
            break;
          }
          case 144: {
            FrequencyTolerance = input.ReadUInt32();
            break;
          }
          case 152: {
            TrPeriod = input.ReadUInt32();
            break;
          }
          case 162: {
            ConfigurationName = input.ReadString();
            break;
          }
          case 170: {
            TxMessage = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DialFrequencyHz = input.ReadUInt64();
            break;
          }
          case 18: {
            Mode = input.ReadString();
            break;
          }
          case 26: {
            DxCall = input.ReadString();
            break;
          }
          case 34: {
            Report = input.ReadString();
            break;
          }
          case 42: {
            TxMode = input.ReadString();
            break;
          }
          case 48: {
            TxEnabled = input.ReadBool();
            break;
          }
          case 56: {
            Transmitting = input.ReadBool();
            break;
          }
          case 64: {
            Decoding = input.ReadBool();
            break;
          }
          case 72: {
            RxOffsetFrequencyHz = input.ReadUInt32();
            break;
          }
          case 80: {
            TxOffsetFrequencyHz = input.ReadUInt32();
            break;
          }
          case 90: {
            DeCall = input.ReadString();
            break;
          }
          case 98: {
            DeGrid = input.ReadString();
            break;
          }
          case 106: {
            DxGrid = input.ReadString();
            break;
          }
          case 112: {
            TxWatchdog = input.ReadBool();
            break;
          }
          case 122: {
            SubMode = input.ReadString();
            break;
          }
          case 128: {
            FastMode = input.ReadBool();
            break;
          }
          case 136: {
            SpecialOperationMode = (global::CloudlogHelper.CLHProto.SpecialOperationMode) input.ReadEnum();
            break;
          }
          case 144: {
            FrequencyTolerance = input.ReadUInt32();
            break;
          }
          case 152: {
            TrPeriod = input.ReadUInt32();
            break;
          }
          case 162: {
            ConfigurationName = input.ReadString();
            break;
          }
          case 170: {
            TxMessage = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
