// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: digmode.proto

package clh_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpecialOperationMode int32

const (
	SpecialOperationMode_NONE     SpecialOperationMode = 0
	SpecialOperationMode_NAVHF    SpecialOperationMode = 1
	SpecialOperationMode_EUVHF    SpecialOperationMode = 3
	SpecialOperationMode_FIELDDAY SpecialOperationMode = 4
	SpecialOperationMode_RTTYRU   SpecialOperationMode = 5
	SpecialOperationMode_FOX      SpecialOperationMode = 6
	SpecialOperationMode_HOUND    SpecialOperationMode = 7
)

// Enum value maps for SpecialOperationMode.
var (
	SpecialOperationMode_name = map[int32]string{
		0: "NONE",
		1: "NAVHF",
		3: "EUVHF",
		4: "FIELDDAY",
		5: "RTTYRU",
		6: "FOX",
		7: "HOUND",
	}
	SpecialOperationMode_value = map[string]int32{
		"NONE":     0,
		"NAVHF":    1,
		"EUVHF":    3,
		"FIELDDAY": 4,
		"RTTYRU":   5,
		"FOX":      6,
		"HOUND":    7,
	}
)

func (x SpecialOperationMode) Enum() *SpecialOperationMode {
	p := new(SpecialOperationMode)
	*p = x
	return p
}

func (x SpecialOperationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpecialOperationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_digmode_proto_enumTypes[0].Descriptor()
}

func (SpecialOperationMode) Type() protoreflect.EnumType {
	return &file_digmode_proto_enumTypes[0]
}

func (x SpecialOperationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpecialOperationMode.Descriptor instead.
func (SpecialOperationMode) EnumDescriptor() ([]byte, []int) {
	return file_digmode_proto_rawDescGZIP(), []int{0}
}

// Server will pack all cached message and send to client at once.
type WsjtxMessagePacked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Decodes       []*Decode              `protobuf:"bytes,2,rep,name=decodes,proto3" json:"decodes,omitempty"`
	WsprDecodes   []*WSPRDecode          `protobuf:"bytes,3,rep,name=wspr_decodes,json=wsprDecodes,proto3" json:"wspr_decodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsjtxMessagePacked) Reset() {
	*x = WsjtxMessagePacked{}
	mi := &file_digmode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsjtxMessagePacked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsjtxMessagePacked) ProtoMessage() {}

func (x *WsjtxMessagePacked) ProtoReflect() protoreflect.Message {
	mi := &file_digmode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsjtxMessagePacked.ProtoReflect.Descriptor instead.
func (*WsjtxMessagePacked) Descriptor() ([]byte, []int) {
	return file_digmode_proto_rawDescGZIP(), []int{0}
}

func (x *WsjtxMessagePacked) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *WsjtxMessagePacked) GetDecodes() []*Decode {
	if x != nil {
		return x.Decodes
	}
	return nil
}

func (x *WsjtxMessagePacked) GetWsprDecodes() []*WSPRDecode {
	if x != nil {
		return x.WsprDecodes
	}
	return nil
}

type WsjtxMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WsjtxMessage_Status
	//	*WsjtxMessage_Decode
	//	*WsjtxMessage_WsprDecode
	Payload       isWsjtxMessage_Payload `protobuf_oneof:"payload"`
	Timestamp     int64                  `protobuf:"varint,100,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsjtxMessage) Reset() {
	*x = WsjtxMessage{}
	mi := &file_digmode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsjtxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsjtxMessage) ProtoMessage() {}

func (x *WsjtxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_digmode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsjtxMessage.ProtoReflect.Descriptor instead.
func (*WsjtxMessage) Descriptor() ([]byte, []int) {
	return file_digmode_proto_rawDescGZIP(), []int{1}
}

func (x *WsjtxMessage) GetPayload() isWsjtxMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WsjtxMessage) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Payload.(*WsjtxMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *WsjtxMessage) GetDecode() *Decode {
	if x != nil {
		if x, ok := x.Payload.(*WsjtxMessage_Decode); ok {
			return x.Decode
		}
	}
	return nil
}

func (x *WsjtxMessage) GetWsprDecode() *WSPRDecode {
	if x != nil {
		if x, ok := x.Payload.(*WsjtxMessage_WsprDecode); ok {
			return x.WsprDecode
		}
	}
	return nil
}

func (x *WsjtxMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type isWsjtxMessage_Payload interface {
	isWsjtxMessage_Payload()
}

type WsjtxMessage_Status struct {
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type WsjtxMessage_Decode struct {
	Decode *Decode `protobuf:"bytes,2,opt,name=decode,proto3,oneof"`
}

type WsjtxMessage_WsprDecode struct {
	WsprDecode *WSPRDecode `protobuf:"bytes,3,opt,name=wspr_decode,json=wsprDecode,proto3,oneof"`
}

func (*WsjtxMessage_Status) isWsjtxMessage_Payload() {}

func (*WsjtxMessage_Decode) isWsjtxMessage_Payload() {}

func (*WsjtxMessage_WsprDecode) isWsjtxMessage_Payload() {}

type Decode struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	New               bool                   `protobuf:"varint,1,opt,name=new,proto3" json:"new,omitempty"`
	Time              uint32                 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Snr               int32                  `protobuf:"varint,3,opt,name=snr,proto3" json:"snr,omitempty"`
	OffsetTimeSeconds float32                `protobuf:"fixed32,4,opt,name=offset_time_seconds,json=offsetTimeSeconds,proto3" json:"offset_time_seconds,omitempty"`
	OffsetFrequencyHz float32                `protobuf:"fixed32,5,opt,name=offset_frequency_hz,json=offsetFrequencyHz,proto3" json:"offset_frequency_hz,omitempty"`
	Mode              string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	Message           string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	LowConfidence     bool                   `protobuf:"varint,8,opt,name=low_confidence,json=lowConfidence,proto3" json:"low_confidence,omitempty"`
	OffAir            bool                   `protobuf:"varint,9,opt,name=off_air,json=offAir,proto3" json:"off_air,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Decode) Reset() {
	*x = Decode{}
	mi := &file_digmode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decode) ProtoMessage() {}

func (x *Decode) ProtoReflect() protoreflect.Message {
	mi := &file_digmode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decode.ProtoReflect.Descriptor instead.
func (*Decode) Descriptor() ([]byte, []int) {
	return file_digmode_proto_rawDescGZIP(), []int{2}
}

func (x *Decode) GetNew() bool {
	if x != nil {
		return x.New
	}
	return false
}

func (x *Decode) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Decode) GetSnr() int32 {
	if x != nil {
		return x.Snr
	}
	return 0
}

func (x *Decode) GetOffsetTimeSeconds() float32 {
	if x != nil {
		return x.OffsetTimeSeconds
	}
	return 0
}

func (x *Decode) GetOffsetFrequencyHz() float32 {
	if x != nil {
		return x.OffsetFrequencyHz
	}
	return 0
}

func (x *Decode) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Decode) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Decode) GetLowConfidence() bool {
	if x != nil {
		return x.LowConfidence
	}
	return false
}

func (x *Decode) GetOffAir() bool {
	if x != nil {
		return x.OffAir
	}
	return false
}

type WSPRDecode struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	New              bool                   `protobuf:"varint,1,opt,name=new,proto3" json:"new,omitempty"`
	Time             uint32                 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Snr              int32                  `protobuf:"varint,3,opt,name=snr,proto3" json:"snr,omitempty"`
	DeltaTimeSeconds float32                `protobuf:"fixed32,4,opt,name=delta_time_seconds,json=deltaTimeSeconds,proto3" json:"delta_time_seconds,omitempty"`
	FrequencyHz      uint64                 `protobuf:"varint,5,opt,name=frequency_hz,json=frequencyHz,proto3" json:"frequency_hz,omitempty"`
	FrequencyDriftHz int32                  `protobuf:"varint,6,opt,name=frequency_drift_hz,json=frequencyDriftHz,proto3" json:"frequency_drift_hz,omitempty"`
	Callsign         string                 `protobuf:"bytes,7,opt,name=callsign,proto3" json:"callsign,omitempty"`
	Grid             string                 `protobuf:"bytes,8,opt,name=grid,proto3" json:"grid,omitempty"`
	Power            uint32                 `protobuf:"varint,9,opt,name=power,proto3" json:"power,omitempty"`
	OffAir           bool                   `protobuf:"varint,10,opt,name=off_air,json=offAir,proto3" json:"off_air,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WSPRDecode) Reset() {
	*x = WSPRDecode{}
	mi := &file_digmode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSPRDecode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSPRDecode) ProtoMessage() {}

func (x *WSPRDecode) ProtoReflect() protoreflect.Message {
	mi := &file_digmode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSPRDecode.ProtoReflect.Descriptor instead.
func (*WSPRDecode) Descriptor() ([]byte, []int) {
	return file_digmode_proto_rawDescGZIP(), []int{3}
}

func (x *WSPRDecode) GetNew() bool {
	if x != nil {
		return x.New
	}
	return false
}

func (x *WSPRDecode) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *WSPRDecode) GetSnr() int32 {
	if x != nil {
		return x.Snr
	}
	return 0
}

func (x *WSPRDecode) GetDeltaTimeSeconds() float32 {
	if x != nil {
		return x.DeltaTimeSeconds
	}
	return 0
}

func (x *WSPRDecode) GetFrequencyHz() uint64 {
	if x != nil {
		return x.FrequencyHz
	}
	return 0
}

func (x *WSPRDecode) GetFrequencyDriftHz() int32 {
	if x != nil {
		return x.FrequencyDriftHz
	}
	return 0
}

func (x *WSPRDecode) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *WSPRDecode) GetGrid() string {
	if x != nil {
		return x.Grid
	}
	return ""
}

func (x *WSPRDecode) GetPower() uint32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *WSPRDecode) GetOffAir() bool {
	if x != nil {
		return x.OffAir
	}
	return false
}

type Status struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DialFrequencyHz      uint64                 `protobuf:"varint,1,opt,name=dial_frequency_hz,json=dialFrequencyHz,proto3" json:"dial_frequency_hz,omitempty"`
	Mode                 string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	DxCall               string                 `protobuf:"bytes,3,opt,name=dx_call,json=dxCall,proto3" json:"dx_call,omitempty"`
	Report               string                 `protobuf:"bytes,4,opt,name=report,proto3" json:"report,omitempty"`
	TxMode               string                 `protobuf:"bytes,5,opt,name=tx_mode,json=txMode,proto3" json:"tx_mode,omitempty"`
	TxEnabled            bool                   `protobuf:"varint,6,opt,name=tx_enabled,json=txEnabled,proto3" json:"tx_enabled,omitempty"`
	Transmitting         bool                   `protobuf:"varint,7,opt,name=transmitting,proto3" json:"transmitting,omitempty"`
	Decoding             bool                   `protobuf:"varint,8,opt,name=decoding,proto3" json:"decoding,omitempty"`
	RxOffsetFrequencyHz  uint32                 `protobuf:"varint,9,opt,name=rx_offset_frequency_hz,json=rxOffsetFrequencyHz,proto3" json:"rx_offset_frequency_hz,omitempty"`
	TxOffsetFrequencyHz  uint32                 `protobuf:"varint,10,opt,name=tx_offset_frequency_hz,json=txOffsetFrequencyHz,proto3" json:"tx_offset_frequency_hz,omitempty"`
	DeCall               string                 `protobuf:"bytes,11,opt,name=de_call,json=deCall,proto3" json:"de_call,omitempty"`
	DeGrid               string                 `protobuf:"bytes,12,opt,name=de_grid,json=deGrid,proto3" json:"de_grid,omitempty"`
	DxGrid               string                 `protobuf:"bytes,13,opt,name=dx_grid,json=dxGrid,proto3" json:"dx_grid,omitempty"`
	TxWatchdog           bool                   `protobuf:"varint,14,opt,name=tx_watchdog,json=txWatchdog,proto3" json:"tx_watchdog,omitempty"`
	SubMode              string                 `protobuf:"bytes,15,opt,name=sub_mode,json=subMode,proto3" json:"sub_mode,omitempty"`
	FastMode             bool                   `protobuf:"varint,16,opt,name=fast_mode,json=fastMode,proto3" json:"fast_mode,omitempty"`
	SpecialOperationMode SpecialOperationMode   `protobuf:"varint,17,opt,name=special_operation_mode,json=specialOperationMode,proto3,enum=clh_proto.msg.SpecialOperationMode" json:"special_operation_mode,omitempty"`
	FrequencyTolerance   uint32                 `protobuf:"varint,18,opt,name=frequency_tolerance,json=frequencyTolerance,proto3" json:"frequency_tolerance,omitempty"`
	TrPeriod             uint32                 `protobuf:"varint,19,opt,name=tr_period,json=trPeriod,proto3" json:"tr_period,omitempty"`
	ConfigurationName    string                 `protobuf:"bytes,20,opt,name=configuration_name,json=configurationName,proto3" json:"configuration_name,omitempty"`
	TxMessage            string                 `protobuf:"bytes,21,opt,name=tx_message,json=txMessage,proto3" json:"tx_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_digmode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_digmode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_digmode_proto_rawDescGZIP(), []int{4}
}

func (x *Status) GetDialFrequencyHz() uint64 {
	if x != nil {
		return x.DialFrequencyHz
	}
	return 0
}

func (x *Status) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Status) GetDxCall() string {
	if x != nil {
		return x.DxCall
	}
	return ""
}

func (x *Status) GetReport() string {
	if x != nil {
		return x.Report
	}
	return ""
}

func (x *Status) GetTxMode() string {
	if x != nil {
		return x.TxMode
	}
	return ""
}

func (x *Status) GetTxEnabled() bool {
	if x != nil {
		return x.TxEnabled
	}
	return false
}

func (x *Status) GetTransmitting() bool {
	if x != nil {
		return x.Transmitting
	}
	return false
}

func (x *Status) GetDecoding() bool {
	if x != nil {
		return x.Decoding
	}
	return false
}

func (x *Status) GetRxOffsetFrequencyHz() uint32 {
	if x != nil {
		return x.RxOffsetFrequencyHz
	}
	return 0
}

func (x *Status) GetTxOffsetFrequencyHz() uint32 {
	if x != nil {
		return x.TxOffsetFrequencyHz
	}
	return 0
}

func (x *Status) GetDeCall() string {
	if x != nil {
		return x.DeCall
	}
	return ""
}

func (x *Status) GetDeGrid() string {
	if x != nil {
		return x.DeGrid
	}
	return ""
}

func (x *Status) GetDxGrid() string {
	if x != nil {
		return x.DxGrid
	}
	return ""
}

func (x *Status) GetTxWatchdog() bool {
	if x != nil {
		return x.TxWatchdog
	}
	return false
}

func (x *Status) GetSubMode() string {
	if x != nil {
		return x.SubMode
	}
	return ""
}

func (x *Status) GetFastMode() bool {
	if x != nil {
		return x.FastMode
	}
	return false
}

func (x *Status) GetSpecialOperationMode() SpecialOperationMode {
	if x != nil {
		return x.SpecialOperationMode
	}
	return SpecialOperationMode_NONE
}

func (x *Status) GetFrequencyTolerance() uint32 {
	if x != nil {
		return x.FrequencyTolerance
	}
	return 0
}

func (x *Status) GetTrPeriod() uint32 {
	if x != nil {
		return x.TrPeriod
	}
	return 0
}

func (x *Status) GetConfigurationName() string {
	if x != nil {
		return x.ConfigurationName
	}
	return ""
}

func (x *Status) GetTxMessage() string {
	if x != nil {
		return x.TxMessage
	}
	return ""
}

var File_digmode_proto protoreflect.FileDescriptor

const file_digmode_proto_rawDesc = "" +
	"\n" +
	"\rdigmode.proto\x12\rclh_proto.msg\"\xb2\x01\n" +
	"\x12WsjtxMessagePacked\x12-\n" +
	"\x06status\x18\x01 \x01(\v2\x15.clh_proto.msg.StatusR\x06status\x12/\n" +
	"\adecodes\x18\x02 \x03(\v2\x15.clh_proto.msg.DecodeR\adecodes\x12<\n" +
	"\fwspr_decodes\x18\x03 \x03(\v2\x19.clh_proto.msg.WSPRDecodeR\vwsprDecodes\"\xd7\x01\n" +
	"\fWsjtxMessage\x12/\n" +
	"\x06status\x18\x01 \x01(\v2\x15.clh_proto.msg.StatusH\x00R\x06status\x12/\n" +
	"\x06decode\x18\x02 \x01(\v2\x15.clh_proto.msg.DecodeH\x00R\x06decode\x12<\n" +
	"\vwspr_decode\x18\x03 \x01(\v2\x19.clh_proto.msg.WSPRDecodeH\x00R\n" +
	"wsprDecode\x12\x1c\n" +
	"\ttimestamp\x18d \x01(\x03R\ttimestampB\t\n" +
	"\apayload\"\x8e\x02\n" +
	"\x06Decode\x12\x10\n" +
	"\x03new\x18\x01 \x01(\bR\x03new\x12\x12\n" +
	"\x04time\x18\x02 \x01(\rR\x04time\x12\x10\n" +
	"\x03snr\x18\x03 \x01(\x05R\x03snr\x12.\n" +
	"\x13offset_time_seconds\x18\x04 \x01(\x02R\x11offsetTimeSeconds\x12.\n" +
	"\x13offset_frequency_hz\x18\x05 \x01(\x02R\x11offsetFrequencyHz\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12%\n" +
	"\x0elow_confidence\x18\b \x01(\bR\rlowConfidence\x12\x17\n" +
	"\aoff_air\x18\t \x01(\bR\x06offAir\"\xa2\x02\n" +
	"\n" +
	"WSPRDecode\x12\x10\n" +
	"\x03new\x18\x01 \x01(\bR\x03new\x12\x12\n" +
	"\x04time\x18\x02 \x01(\rR\x04time\x12\x10\n" +
	"\x03snr\x18\x03 \x01(\x05R\x03snr\x12,\n" +
	"\x12delta_time_seconds\x18\x04 \x01(\x02R\x10deltaTimeSeconds\x12!\n" +
	"\ffrequency_hz\x18\x05 \x01(\x04R\vfrequencyHz\x12,\n" +
	"\x12frequency_drift_hz\x18\x06 \x01(\x05R\x10frequencyDriftHz\x12\x1a\n" +
	"\bcallsign\x18\a \x01(\tR\bcallsign\x12\x12\n" +
	"\x04grid\x18\b \x01(\tR\x04grid\x12\x14\n" +
	"\x05power\x18\t \x01(\rR\x05power\x12\x17\n" +
	"\aoff_air\x18\n" +
	" \x01(\bR\x06offAir\"\xf6\x05\n" +
	"\x06Status\x12*\n" +
	"\x11dial_frequency_hz\x18\x01 \x01(\x04R\x0fdialFrequencyHz\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x17\n" +
	"\adx_call\x18\x03 \x01(\tR\x06dxCall\x12\x16\n" +
	"\x06report\x18\x04 \x01(\tR\x06report\x12\x17\n" +
	"\atx_mode\x18\x05 \x01(\tR\x06txMode\x12\x1d\n" +
	"\n" +
	"tx_enabled\x18\x06 \x01(\bR\ttxEnabled\x12\"\n" +
	"\ftransmitting\x18\a \x01(\bR\ftransmitting\x12\x1a\n" +
	"\bdecoding\x18\b \x01(\bR\bdecoding\x123\n" +
	"\x16rx_offset_frequency_hz\x18\t \x01(\rR\x13rxOffsetFrequencyHz\x123\n" +
	"\x16tx_offset_frequency_hz\x18\n" +
	" \x01(\rR\x13txOffsetFrequencyHz\x12\x17\n" +
	"\ade_call\x18\v \x01(\tR\x06deCall\x12\x17\n" +
	"\ade_grid\x18\f \x01(\tR\x06deGrid\x12\x17\n" +
	"\adx_grid\x18\r \x01(\tR\x06dxGrid\x12\x1f\n" +
	"\vtx_watchdog\x18\x0e \x01(\bR\n" +
	"txWatchdog\x12\x19\n" +
	"\bsub_mode\x18\x0f \x01(\tR\asubMode\x12\x1b\n" +
	"\tfast_mode\x18\x10 \x01(\bR\bfastMode\x12Y\n" +
	"\x16special_operation_mode\x18\x11 \x01(\x0e2#.clh_proto.msg.SpecialOperationModeR\x14specialOperationMode\x12/\n" +
	"\x13frequency_tolerance\x18\x12 \x01(\rR\x12frequencyTolerance\x12\x1b\n" +
	"\ttr_period\x18\x13 \x01(\rR\btrPeriod\x12-\n" +
	"\x12configuration_name\x18\x14 \x01(\tR\x11configurationName\x12\x1d\n" +
	"\n" +
	"tx_message\x18\x15 \x01(\tR\ttxMessage*d\n" +
	"\x14SpecialOperationMode\x12\b\n" +
	"\x04NONE\x10\x00\x12\t\n" +
	"\x05NAVHF\x10\x01\x12\t\n" +
	"\x05EUVHF\x10\x03\x12\f\n" +
	"\bFIELDDAY\x10\x04\x12\n" +
	"\n" +
	"\x06RTTYRU\x10\x05\x12\a\n" +
	"\x03FOX\x10\x06\x12\t\n" +
	"\x05HOUND\x10\aBEZ)github.com/sydneyowl/clh-server/clh-proto\xaa\x02\x17CloudlogHelper.CLHProtob\x06proto3"

var (
	file_digmode_proto_rawDescOnce sync.Once
	file_digmode_proto_rawDescData []byte
)

func file_digmode_proto_rawDescGZIP() []byte {
	file_digmode_proto_rawDescOnce.Do(func() {
		file_digmode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_digmode_proto_rawDesc), len(file_digmode_proto_rawDesc)))
	})
	return file_digmode_proto_rawDescData
}

var file_digmode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_digmode_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_digmode_proto_goTypes = []any{
	(SpecialOperationMode)(0),  // 0: clh_proto.msg.SpecialOperationMode
	(*WsjtxMessagePacked)(nil), // 1: clh_proto.msg.WsjtxMessagePacked
	(*WsjtxMessage)(nil),       // 2: clh_proto.msg.WsjtxMessage
	(*Decode)(nil),             // 3: clh_proto.msg.Decode
	(*WSPRDecode)(nil),         // 4: clh_proto.msg.WSPRDecode
	(*Status)(nil),             // 5: clh_proto.msg.Status
}
var file_digmode_proto_depIdxs = []int32{
	5, // 0: clh_proto.msg.WsjtxMessagePacked.status:type_name -> clh_proto.msg.Status
	3, // 1: clh_proto.msg.WsjtxMessagePacked.decodes:type_name -> clh_proto.msg.Decode
	4, // 2: clh_proto.msg.WsjtxMessagePacked.wspr_decodes:type_name -> clh_proto.msg.WSPRDecode
	5, // 3: clh_proto.msg.WsjtxMessage.status:type_name -> clh_proto.msg.Status
	3, // 4: clh_proto.msg.WsjtxMessage.decode:type_name -> clh_proto.msg.Decode
	4, // 5: clh_proto.msg.WsjtxMessage.wspr_decode:type_name -> clh_proto.msg.WSPRDecode
	0, // 6: clh_proto.msg.Status.special_operation_mode:type_name -> clh_proto.msg.SpecialOperationMode
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_digmode_proto_init() }
func file_digmode_proto_init() {
	if File_digmode_proto != nil {
		return
	}
	file_digmode_proto_msgTypes[1].OneofWrappers = []any{
		(*WsjtxMessage_Status)(nil),
		(*WsjtxMessage_Decode)(nil),
		(*WsjtxMessage_WsprDecode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_digmode_proto_rawDesc), len(file_digmode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_digmode_proto_goTypes,
		DependencyIndexes: file_digmode_proto_depIdxs,
		EnumInfos:         file_digmode_proto_enumTypes,
		MessageInfos:      file_digmode_proto_msgTypes,
	}.Build()
	File_digmode_proto = out.File
	file_digmode_proto_goTypes = nil
	file_digmode_proto_depIdxs = nil
}
