// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rig.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CloudlogHelper.CLHProto {

  /// <summary>Holder for reflection information generated from rig.proto</summary>
  public static partial class RigReflection {

    #region Descriptor
    /// <summary>File descriptor for rig.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CglyaWcucHJvdG8SDWNsaF9wcm90by5tc2cikwEKB1JpZ0RhdGESEAoIcHJv",
            "dmlkZXIYASABKAkSEAoIcmlnX25hbWUYAiABKAkSEQoJZnJlcXVlbmN5GAMg",
            "ASgEEgwKBG1vZGUYBCABKAkSFAoMZnJlcXVlbmN5X3J4GAUgASgEEg8KB21v",
            "ZGVfcngYBiABKAkSDQoFc3BsaXQYByABKAgSDQoFcG93ZXIYCCABKA1CRVop",
            "Z2l0aHViLmNvbS9zeWRuZXlvd2wvY2xoLXNlcnZlci9jbGgtcHJvdG+qAhdD",
            "bG91ZGxvZ0hlbHBlci5DTEhQcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CloudlogHelper.CLHProto.RigData), global::CloudlogHelper.CLHProto.RigData.Parser, new[]{ "Provider", "RigName", "Frequency", "Mode", "FrequencyRx", "ModeRx", "Split", "Power" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RigData : pb::IMessage<RigData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RigData> _parser = new pb::MessageParser<RigData>(() => new RigData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RigData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CloudlogHelper.CLHProto.RigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RigData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RigData(RigData other) : this() {
      provider_ = other.provider_;
      rigName_ = other.rigName_;
      frequency_ = other.frequency_;
      mode_ = other.mode_;
      frequencyRx_ = other.frequencyRx_;
      modeRx_ = other.modeRx_;
      split_ = other.split_;
      power_ = other.power_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RigData Clone() {
      return new RigData(this);
    }

    /// <summary>Field number for the "provider" field.</summary>
    public const int ProviderFieldNumber = 1;
    private string provider_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Provider {
      get { return provider_; }
      set {
        provider_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rig_name" field.</summary>
    public const int RigNameFieldNumber = 2;
    private string rigName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RigName {
      get { return rigName_; }
      set {
        rigName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "frequency" field.</summary>
    public const int FrequencyFieldNumber = 3;
    private ulong frequency_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Frequency {
      get { return frequency_; }
      set {
        frequency_ = value;
      }
    }

    /// <summary>Field number for the "mode" field.</summary>
    public const int ModeFieldNumber = 4;
    private string mode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Mode {
      get { return mode_; }
      set {
        mode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "frequency_rx" field.</summary>
    public const int FrequencyRxFieldNumber = 5;
    private ulong frequencyRx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong FrequencyRx {
      get { return frequencyRx_; }
      set {
        frequencyRx_ = value;
      }
    }

    /// <summary>Field number for the "mode_rx" field.</summary>
    public const int ModeRxFieldNumber = 6;
    private string modeRx_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ModeRx {
      get { return modeRx_; }
      set {
        modeRx_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "split" field.</summary>
    public const int SplitFieldNumber = 7;
    private bool split_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Split {
      get { return split_; }
      set {
        split_ = value;
      }
    }

    /// <summary>Field number for the "power" field.</summary>
    public const int PowerFieldNumber = 8;
    private uint power_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Power {
      get { return power_; }
      set {
        power_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RigData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RigData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Provider != other.Provider) return false;
      if (RigName != other.RigName) return false;
      if (Frequency != other.Frequency) return false;
      if (Mode != other.Mode) return false;
      if (FrequencyRx != other.FrequencyRx) return false;
      if (ModeRx != other.ModeRx) return false;
      if (Split != other.Split) return false;
      if (Power != other.Power) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Provider.Length != 0) hash ^= Provider.GetHashCode();
      if (RigName.Length != 0) hash ^= RigName.GetHashCode();
      if (Frequency != 0UL) hash ^= Frequency.GetHashCode();
      if (Mode.Length != 0) hash ^= Mode.GetHashCode();
      if (FrequencyRx != 0UL) hash ^= FrequencyRx.GetHashCode();
      if (ModeRx.Length != 0) hash ^= ModeRx.GetHashCode();
      if (Split != false) hash ^= Split.GetHashCode();
      if (Power != 0) hash ^= Power.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Provider.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Provider);
      }
      if (RigName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RigName);
      }
      if (Frequency != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Frequency);
      }
      if (Mode.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Mode);
      }
      if (FrequencyRx != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(FrequencyRx);
      }
      if (ModeRx.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ModeRx);
      }
      if (Split != false) {
        output.WriteRawTag(56);
        output.WriteBool(Split);
      }
      if (Power != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(Power);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Provider.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Provider);
      }
      if (RigName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RigName);
      }
      if (Frequency != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Frequency);
      }
      if (Mode.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Mode);
      }
      if (FrequencyRx != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(FrequencyRx);
      }
      if (ModeRx.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ModeRx);
      }
      if (Split != false) {
        output.WriteRawTag(56);
        output.WriteBool(Split);
      }
      if (Power != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(Power);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Provider.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Provider);
      }
      if (RigName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RigName);
      }
      if (Frequency != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Frequency);
      }
      if (Mode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mode);
      }
      if (FrequencyRx != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(FrequencyRx);
      }
      if (ModeRx.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ModeRx);
      }
      if (Split != false) {
        size += 1 + 1;
      }
      if (Power != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Power);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RigData other) {
      if (other == null) {
        return;
      }
      if (other.Provider.Length != 0) {
        Provider = other.Provider;
      }
      if (other.RigName.Length != 0) {
        RigName = other.RigName;
      }
      if (other.Frequency != 0UL) {
        Frequency = other.Frequency;
      }
      if (other.Mode.Length != 0) {
        Mode = other.Mode;
      }
      if (other.FrequencyRx != 0UL) {
        FrequencyRx = other.FrequencyRx;
      }
      if (other.ModeRx.Length != 0) {
        ModeRx = other.ModeRx;
      }
      if (other.Split != false) {
        Split = other.Split;
      }
      if (other.Power != 0) {
        Power = other.Power;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Provider = input.ReadString();
            break;
          }
          case 18: {
            RigName = input.ReadString();
            break;
          }
          case 24: {
            Frequency = input.ReadUInt64();
            break;
          }
          case 34: {
            Mode = input.ReadString();
            break;
          }
          case 40: {
            FrequencyRx = input.ReadUInt64();
            break;
          }
          case 50: {
            ModeRx = input.ReadString();
            break;
          }
          case 56: {
            Split = input.ReadBool();
            break;
          }
          case 64: {
            Power = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Provider = input.ReadString();
            break;
          }
          case 18: {
            RigName = input.ReadString();
            break;
          }
          case 24: {
            Frequency = input.ReadUInt64();
            break;
          }
          case 34: {
            Mode = input.ReadString();
            break;
          }
          case 40: {
            FrequencyRx = input.ReadUInt64();
            break;
          }
          case 50: {
            ModeRx = input.ReadString();
            break;
          }
          case 56: {
            Split = input.ReadBool();
            break;
          }
          case 64: {
            Power = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
