// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rig.proto

package clh_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RigData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	RigName       string                 `protobuf:"bytes,2,opt,name=rig_name,json=rigName,proto3" json:"rig_name,omitempty"`
	Frequency     uint64                 `protobuf:"varint,3,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	FrequencyRx   uint64                 `protobuf:"varint,5,opt,name=frequency_rx,json=frequencyRx,proto3" json:"frequency_rx,omitempty"`
	ModeRx        string                 `protobuf:"bytes,6,opt,name=mode_rx,json=modeRx,proto3" json:"mode_rx,omitempty"`
	Split         bool                   `protobuf:"varint,7,opt,name=split,proto3" json:"split,omitempty"`
	Power         uint32                 `protobuf:"varint,8,opt,name=power,proto3" json:"power,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RigData) Reset() {
	*x = RigData{}
	mi := &file_rig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RigData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RigData) ProtoMessage() {}

func (x *RigData) ProtoReflect() protoreflect.Message {
	mi := &file_rig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RigData.ProtoReflect.Descriptor instead.
func (*RigData) Descriptor() ([]byte, []int) {
	return file_rig_proto_rawDescGZIP(), []int{0}
}

func (x *RigData) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RigData) GetRigName() string {
	if x != nil {
		return x.RigName
	}
	return ""
}

func (x *RigData) GetFrequency() uint64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *RigData) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RigData) GetFrequencyRx() uint64 {
	if x != nil {
		return x.FrequencyRx
	}
	return 0
}

func (x *RigData) GetModeRx() string {
	if x != nil {
		return x.ModeRx
	}
	return ""
}

func (x *RigData) GetSplit() bool {
	if x != nil {
		return x.Split
	}
	return false
}

func (x *RigData) GetPower() uint32 {
	if x != nil {
		return x.Power
	}
	return 0
}

var File_rig_proto protoreflect.FileDescriptor

const file_rig_proto_rawDesc = "" +
	"\n" +
	"\trig.proto\x12\rclh_proto.msg\"\xda\x01\n" +
	"\aRigData\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x19\n" +
	"\brig_name\x18\x02 \x01(\tR\arigName\x12\x1c\n" +
	"\tfrequency\x18\x03 \x01(\x04R\tfrequency\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12!\n" +
	"\ffrequency_rx\x18\x05 \x01(\x04R\vfrequencyRx\x12\x17\n" +
	"\amode_rx\x18\x06 \x01(\tR\x06modeRx\x12\x14\n" +
	"\x05split\x18\a \x01(\bR\x05split\x12\x14\n" +
	"\x05power\x18\b \x01(\rR\x05powerBEZ)github.com/sydneyowl/clh-server/clh-proto\xaa\x02\x17CloudlogHelper.CLHProtob\x06proto3"

var (
	file_rig_proto_rawDescOnce sync.Once
	file_rig_proto_rawDescData []byte
)

func file_rig_proto_rawDescGZIP() []byte {
	file_rig_proto_rawDescOnce.Do(func() {
		file_rig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rig_proto_rawDesc), len(file_rig_proto_rawDesc)))
	})
	return file_rig_proto_rawDescData
}

var file_rig_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rig_proto_goTypes = []any{
	(*RigData)(nil), // 0: clh_proto.msg.RigData
}
var file_rig_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rig_proto_init() }
func file_rig_proto_init() {
	if File_rig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rig_proto_rawDesc), len(file_rig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rig_proto_goTypes,
		DependencyIndexes: file_rig_proto_depIdxs,
		MessageInfos:      file_rig_proto_msgTypes,
	}.Build()
	File_rig_proto = out.File
	file_rig_proto_goTypes = nil
	file_rig_proto_depIdxs = nil
}
